version: '3.7'

services:
  kma-gear-frontend:
    build:
      context: ./
      target: development
    
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: always